# Form implementation generated from reading ui file 'C:\Users\User\Desktop\NHOM-5_KTLTNC\Giao diện\CHINH.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1258, 861)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("\n"
"QMainWindow{\n"
"    background:#f5f7fb;\n"
"}\n"
"\n"
"QFrame{\n"
"    background:white;\n"
"    border:1px solid #e5e7eb;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background:white;\n"
"    color:#374151;\n"
"    border:1px solid #d1d5db;\n"
"    border-radius:8px;\n"
"    padding:8px;\n"
"    font-weight:600;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background:#eff6ff;\n"
"    border:1px solid #60a5fa;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background:#dbeafe;\n"
"}\n"
"\n"
"QLineEdit,QComboBox{\n"
"    background:white;\n"
"    border:1px solid #d1d5db;\n"
"    border-radius:8px;\n"
"    padding:6px;\n"
"}\n"
"\n"
"QTreeView,QTableView{\n"
"    background:white;\n"
"    border:1px solid #d1d5db;\n"
"    alternate-background-color:#f8fafc;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    background:#2563eb;\n"
"    color:white;\n"
"    border:none;\n"
"    padding:6px;\n"
"    font-weight:bold;\n"
"}\n"
"\n"
"QTabBar::tab{\n"
"    background:#eef2ff;\n"
"    padding:8px 16px;\n"
"    border-top-left-radius:8px;\n"
"    border-top-right-radius:8px;\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"    background:white;\n"
"    border-bottom:2px solid #2563eb;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lowerframe = QtWidgets.QFrame(parent=self.centralwidget)
        self.lowerframe.setGeometry(QtCore.QRect(-10, 100, 1261, 721))
        self.lowerframe.setStyleSheet("background-color:rgb(223, 223, 223)")
        self.lowerframe.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.lowerframe.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.lowerframe.setObjectName("lowerframe")
        self.tableView = QtWidgets.QTableView(parent=self.lowerframe)
        self.tableView.setGeometry(QtCore.QRect(350, 130, 901, 581))
        self.tableView.setObjectName("tableView")
        self.frame_6 = QtWidgets.QFrame(parent=self.lowerframe)
        self.frame_6.setGeometry(QtCore.QRect(10, 10, 1241, 111))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.frame_6.setFont(font)
        self.frame_6.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.btnHome = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnHome.setGeometry(QtCore.QRect(10, 0, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnHome.setFont(font)
        self.btnHome.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.btnHome.setObjectName("btnHome")
        self.txtPath = QtWidgets.QLineEdit(parent=self.frame_6)
        self.txtPath.setGeometry(QtCore.QRect(250, 0, 991, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtPath.setFont(font)
        self.txtPath.setText("")
        self.txtPath.setReadOnly(True)
        self.txtPath.setObjectName("txtPath")
        self.btnBack = QtWidgets.QPushButton(parent=self.frame_6)
        self.btnBack.setGeometry(QtCore.QRect(130, 0, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnBack.setFont(font)
        self.btnBack.setObjectName("btnBack")
        self.txtSearch = QtWidgets.QLineEdit(parent=self.frame_6)
        self.txtSearch.setGeometry(QtCore.QRect(610, 60, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtSearch.setFont(font)
        self.txtSearch.setObjectName("txtSearch")
        self.cboFilter = QtWidgets.QComboBox(parent=self.frame_6)
        self.cboFilter.setGeometry(QtCore.QRect(1120, 60, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cboFilter.setFont(font)
        self.cboFilter.setMaxVisibleItems(10)
        self.cboFilter.setObjectName("cboFilter")
        self.cboFilter.addItem("")
        self.cboFilter.addItem("")
        self.cboFilter.addItem("")
        self.cboFilter.addItem("")
        self.cboFilter.addItem("")
        self.cboFilter.addItem("")
        self.treeView = QtWidgets.QTreeView(parent=self.lowerframe)
        self.treeView.setGeometry(QtCore.QRect(10, 130, 331, 581))
        self.treeView.setObjectName("treeView")
        self.upperframe = QtWidgets.QFrame(parent=self.centralwidget)
        self.upperframe.setGeometry(QtCore.QRect(-10, -10, 1301, 101))
        self.upperframe.setStyleSheet("background - color: rgb(255, 255, 255)")
        self.upperframe.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.upperframe.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.upperframe.setObjectName("upperframe")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.upperframe)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 1231, 101))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.tabWidget.setObjectName("tabWidget")
        self.File = QtWidgets.QWidget()
        self.File.setWhatsThis("")
        self.File.setObjectName("File")
        self.frame = QtWidgets.QFrame(parent=self.File)
        self.frame.setGeometry(QtCore.QRect(0, 0, 891, 51))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.btnNewfolder = QtWidgets.QToolButton(parent=self.frame)
        self.btnNewfolder.setGeometry(QtCore.QRect(0, 0, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnNewfolder.setFont(font)
        self.btnNewfolder.setObjectName("btnNewfolder")
        self.btnOpen = QtWidgets.QToolButton(parent=self.frame)
        self.btnOpen.setGeometry(QtCore.QRect(200, 0, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnOpen.setFont(font)
        self.btnOpen.setObjectName("btnOpen")
        self.btnSave = QtWidgets.QToolButton(parent=self.frame)
        self.btnSave.setGeometry(QtCore.QRect(400, 0, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnSave.setFont(font)
        self.btnSave.setAutoRepeat(False)
        self.btnSave.setObjectName("btnSave")
        self.tabWidget.addTab(self.File, "")
        self.edit = QtWidgets.QWidget()
        self.edit.setObjectName("edit")
        self.frame_2 = QtWidgets.QFrame(parent=self.edit)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1041, 51))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btnAddFile = QtWidgets.QToolButton(parent=self.frame_2)
        self.btnAddFile.setGeometry(QtCore.QRect(0, 0, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnAddFile.setFont(font)
        self.btnAddFile.setObjectName("btnAddFile")
        self.btnAddFolder = QtWidgets.QToolButton(parent=self.frame_2)
        self.btnAddFolder.setGeometry(QtCore.QRect(200, 0, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnAddFolder.setFont(font)
        self.btnAddFolder.setObjectName("btnAddFolder")
        self.btnRename = QtWidgets.QToolButton(parent=self.frame_2)
        self.btnRename.setGeometry(QtCore.QRect(400, 0, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnRename.setFont(font)
        self.btnRename.setObjectName("btnRename")
        self.btnDelete = QtWidgets.QToolButton(parent=self.frame_2)
        self.btnDelete.setGeometry(QtCore.QRect(600, 0, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnDelete.setFont(font)
        self.btnDelete.setObjectName("btnDelete")
        self.tabWidget.addTab(self.edit, "")
        self.view = QtWidgets.QWidget()
        self.view.setObjectName("view")
        self.frame_3 = QtWidgets.QFrame(parent=self.view)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.btnAllinfo = QtWidgets.QToolButton(parent=self.frame_3)
        self.btnAllinfo.setGeometry(QtCore.QRect(0, 0, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnAllinfo.setFont(font)
        self.btnAllinfo.setObjectName("btnAllinfo")
        self.tabWidget.addTab(self.view, "")
        self.help = QtWidgets.QWidget()
        self.help.setObjectName("help")
        self.frame_4 = QtWidgets.QFrame(parent=self.help)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 1041, 51))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.btnContact = QtWidgets.QToolButton(parent=self.frame_4)
        self.btnContact.setGeometry(QtCore.QRect(0, 0, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnContact.setFont(font)
        self.btnContact.setObjectName("btnContact")
        self.tabWidget.addTab(self.help, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1258, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableView.setStyleSheet(_translate("MainWindow", "background-color:rgb(255, 255, 255)"))
        self.btnHome.setText(_translate("MainWindow", "🏠 Home"))
        self.txtPath.setStyleSheet(_translate("MainWindow", "background-color:rgb(255, 255, 255)"))
        self.txtPath.setPlaceholderText(_translate("MainWindow", "Current Path"))
        self.btnBack.setStyleSheet(_translate("MainWindow", "background-color:rgb(255, 255, 255)"))
        self.btnBack.setText(_translate("MainWindow", "← Back"))
        self.txtSearch.setStyleSheet(_translate("MainWindow", "background-color:rgb(255, 255, 255)"))
        self.txtSearch.setPlaceholderText(_translate("MainWindow", "🔍 Search files..."))
        self.cboFilter.setStyleSheet(_translate("MainWindow", "background-color:rgb(255, 255, 255)"))
        self.cboFilter.setCurrentText(_translate("MainWindow", "All"))
        self.cboFilter.setItemText(0, _translate("MainWindow", "All"))
        self.cboFilter.setItemText(1, _translate("MainWindow", "Folder"))
        self.cboFilter.setItemText(2, _translate("MainWindow", ".txt"))
        self.cboFilter.setItemText(3, _translate("MainWindow", ".pdf"))
        self.cboFilter.setItemText(4, _translate("MainWindow", ".docx"))
        self.cboFilter.setItemText(5, _translate("MainWindow", ".png"))
        self.treeView.setStyleSheet(_translate("MainWindow", "background-color:rgb(255, 255, 255)"))
        self.btnNewfolder.setText(_translate("MainWindow", "📁 New Folder"))
        self.btnOpen.setText(_translate("MainWindow", "📂 Open Folder"))
        self.btnSave.setText(_translate("MainWindow", "💾 Save File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.File), _translate("MainWindow", "File"))
        self.btnAddFile.setText(_translate("MainWindow", "📂➕ Add folder"))
        self.btnAddFolder.setText(_translate("MainWindow", "📄➕ Add File"))
        self.btnRename.setText(_translate("MainWindow", "✏ Rename"))
        self.btnDelete.setText(_translate("MainWindow", "🗑 Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.edit), _translate("MainWindow", "Edit"))
        self.btnAllinfo.setText(_translate("MainWindow", "💡 INFO"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.view), _translate("MainWindow", "View"))
        self.btnContact.setText(_translate("MainWindow", "Contact Us"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.help), _translate("MainWindow", "Help"))
